services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_mine
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: rasla
      MONGO_INITDB_ROOT_PASSWORD: localpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
